// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oysrqferotuvynlmlwfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95c3JxZmVyb3R1dnlubG1sd2ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjkwMzUsImV4cCI6MjA2NTUwNTAzNX0.7bYkjHfdWBSryxq1cw1q06B2XOFZrg2elUX8F-2bLfQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);